### ISSUE TITLE
Pinging the Bot Should Serve Same Function as the Bot Prefix

### ISSUE THREAD

**Issue by Exper1mental** [Clemson-Esports/Reaction-Bot#4]
Pinging the bot at the beginning of a message should be equivalent to invoking the bot prefix. This is useful when folks don't remember what the bot prefix is.
![image](https://user-images.githubusercontent.com/14143235/152688096-b66c63fb-8f60-48e2-bfbf-9b9c3f847ee2.png)

**Comment by TRJoseph** [comment]
How does this look?

<img width="483" alt="Screen Shot 2022-02-07 at 7 35 48 PM" src="https://user-images.githubusercontent.com/83513663/152895779-a0642907-663f-42e3-b2a0-053d060f16d1.png">

**Comment by TRJoseph** [comment]
If you tag the bot it will respond with the help menu

**Comment by Exper1mental** [comment]
I like that!

**Comment by TRJoseph** [comment]
Perfect
